env: multi_cart

env_args:
  cartdist: 1
  num_cartpoles: 3
  obs_radius: 0
  test_physics: False
  episode_limit: 300
  animation_speed: 0
  coupled:
    mode: True
    spring_k: 10.0
    range: 0.1
  rules:
    terminate: "all"   # string, can be any, all, or endless
    edge_springs: True

test_greedy: True
test_nepisode: 10
test_interval: 20000
log_interval: 20000
save_vid_interval: 100000
runner_log_interval: 500
learner_log_interval: 500
t_max: 2000000
